services:
  guitarroom:
    image: guitarroom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_URLS=http://*:6000
    depends_on:
      - peerjs
    command: >
      dotnet GuitarRoom.dll
    networks:
      - guitarroom-network
    volumes:
      - /opt/guitar-room/data:/app/db

  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
    environment:
      - PEER_PORT=9000
      - PEER_PATH=/ 
    networks:
      - guitarroom-network

networks:
  guitarroom-network:
    driver: bridge
